name: "Hello Action"
description: "Greet someone"
author: "thanhka"

input:
  MY_NAME:
    description: "Who to greet"
    required: true
    default: "World"
    
  runs:
    using: "docker"
    image: "Dockerfile"
    
  branding:
    icon: "mic"
    color: "purple"
