name: A workflow for my Hello Word file
on: push
jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - user: actions/checkout@v1
      - user: ./action-a
        with:
          MY_NAME: "Mona"
